server:
  port: 8086
  servlet:
    context-path: /elaparato

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: "jdbc:mysql://localhost:3306/elaparato"
    username: "root"
    password: "root"
    database: elaparato
  application:
      name: elaparato-service
  security:
      oauth2:
          resourceserver:
            jwt:
                issuer-uri: http://localhost:8080/realms/el-aparato-deivid-gonzalez
jwt:
  auth:
    converter:
      resource-id: api-gateway-client
      principal-attribute: preferred_username
